### ISSUE TITLE
哥，打扰一下，我想问下怎样才算精通 js, 精通 vue 呢？

### ISSUE THREAD

**Issue by zhu-hongwei** [yugasun/You-Dont-Know-Vuejs#71]
是这样的：
刚离开学校，找工作。
山东烟台这个地方，前端岗位工作 n 年顶薪1.2-1.5k/月。
很多社招招聘要求精通 xxxxxx，我觉得可能是 hr 不懂技术，发招聘的时候互相复制粘贴罢了。
前天参加面试，8年的前端明确说明确实要求精通 xxxxx（100多人的上市公司，官网没配 https）。
所以我想问一下到什么程度才算是精通 js, 精通 vue 呢，面试时候忘了问他了？

**Comment by yugasun** [comment]
@xiaohongcoder 表示抱歉，现在才看到这个issue，时隔一年不知道你还是否有这个困惑，对于我个人而言，其实也不敢说自己精通，但是一般简历上所谓的精通 Vuejs，我可以直接告诉你的是，大多面试官只是想知道，你是否真正学习过 Vue 框架原理，或者读过核心源码而已。

**Comment by zhu-hongwei** [comment]
谢谢 :-)
